/**
 * Scans public/photos/, sorts filenames numerically, and writes
 * src/data/photos.ts with static imports for Next.js.
 *
 * Usage:
 *   pnpm photos              — regenerate, sort by filename
 *   pnpm photos --keep-order — regenerate, preserve existing order
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from "fs";
import { join, extname } from "path";

const PHOTOS_DIR = join(process.cwd(), "public/photos");
const OUTPUT_FILE = join(process.cwd(), "src/data/photos.ts");
const ALLOWED_EXTS = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif"]);
const keepOrder = process.argv.includes("--keep-order");

// ── 1. Read existing alt text and order from current photos.ts ──────────────

const existingAlts = new Map<string, string>();
const existingOrder: string[] = [];

if (existsSync(OUTPUT_FILE)) {
  const existing = readFileSync(OUTPUT_FILE, "utf8");

  // Map variable name → filename from import lines
  const importMap = new Map<string, string>();
  const importRe = /import\s+(\w+)\s+from\s+"[^"]*\/([^/"]+\.\w+)"/g;
  let m: RegExpExecArray | null;
  while ((m = importRe.exec(existing)) !== null) {
    importMap.set(m[1], m[2]);
    existingOrder.push(m[2]);
  }

  // Map filename → alt from array entries
  const entryRe = /\{\s*src:\s*(\w+),\s*alt:\s*"([^"]*)"\s*\}/g;
  while ((m = entryRe.exec(existing)) !== null) {
    const filename = importMap.get(m[1]);
    if (filename) existingAlts.set(filename, m[2]);
  }
}

// ── 2. Scan photos directory ─────────────────────────────────────────────────

if (!existsSync(PHOTOS_DIR)) {
  console.warn(`⚠  ${PHOTOS_DIR} does not exist — writing empty photos.ts`);
  writeEmpty();
  process.exit(0);
}

const allFiles = readdirSync(PHOTOS_DIR).filter((f) => {
  const ext = extname(f).toLowerCase();
  return ALLOWED_EXTS.has(ext) && !f.startsWith("_");
});

// ── 3. Determine final order ─────────────────────────────────────────────────

let files: string[];

if (keepOrder && existingOrder.length > 0) {
  const allSet = new Set(allFiles);
  const newFiles = allFiles
    .filter((f) => !existingOrder.includes(f))
    .sort(numericLocale);

  files = [
    ...existingOrder.filter((f) => allSet.has(f)),
    ...newFiles,
  ];
} else {
  files = allFiles.slice().sort(numericLocale);
}

// ── 4. Generate file content ─────────────────────────────────────────────────

if (files.length === 0) {
  writeEmpty();
  console.log("✓ No photos found — wrote empty photos.ts");
  process.exit(0);
}

const importLines = files
  .map((f, i) => {
    const varName = makeVarName(i);
    return `import ${varName} from "../../public/photos/${f}";`;
  })
  .join("\n");

const arrayEntries = files
  .map((f, i) => {
    const varName = makeVarName(i);
    const alt = existingAlts.get(f) ?? "";
    return `  { src: ${varName}, alt: "${alt}" }`;
  })
  .join(",\n");

const output = `import type { StaticImageData } from "next/image";
${importLines}

export type Photo = {
  src: StaticImageData;
  alt: string;
};

// Generated by \`pnpm photos\`. Edit alt text freely — it is preserved on re-runs.
// To reorder: run with --keep-order, then manually move entries in this array.
export const photos: Photo[] = [
${arrayEntries},
];
`;

writeFileSync(OUTPUT_FILE, output);
console.log(`✓ Wrote ${files.length} photo${files.length !== 1 ? "s" : ""} to src/data/photos.ts`);

// ── Helpers ───────────────────────────────────────────────────────────────────

function makeVarName(index: number): string {
  return "p" + String(index + 1).padStart(3, "0");
}

function numericLocale(a: string, b: string): number {
  return a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" });
}

function writeEmpty(): void {
  const content = `import type { StaticImageData } from "next/image";

export type Photo = {
  src: StaticImageData;
  alt: string;
};

// Generated by \`pnpm photos\`. Drop images in public/photos/ and re-run.
export const photos: Photo[] = [];
`;
  writeFileSync(OUTPUT_FILE, content);
}
