import type { StaticImageData } from "next/image";
import p001 from "../../public/photos/001.jpg";
import p002 from "../../public/photos/002.jpg";
import p003 from "../../public/photos/003.jpg";
import p004 from "../../public/photos/004.jpg";
import p005 from "../../public/photos/005.jpg";
import p006 from "../../public/photos/006.jpg";
import p007 from "../../public/photos/007.jpg";
import p008 from "../../public/photos/008.jpg";
import p009 from "../../public/photos/009.jpg";
import p010 from "../../public/photos/010.jpg";
import p011 from "../../public/photos/011.jpg";
import p012 from "../../public/photos/012.jpg";
import p013 from "../../public/photos/013.jpg";
import p014 from "../../public/photos/014.jpg";
import p015 from "../../public/photos/015.jpg";
import p016 from "../../public/photos/016.jpg";
import p017 from "../../public/photos/017.jpg";
import p018 from "../../public/photos/018.jpg";
import p019 from "../../public/photos/019.jpg";
import p020 from "../../public/photos/020.jpg";

export type Photo = {
  src: StaticImageData;
  alt: string;
};

// Generated by `pnpm photos`. Edit alt text freely — it is preserved on re-runs.
// To reorder: run with --keep-order, then manually move entries in this array.
export const photos: Photo[] = [
  { src: p001, alt: "" },
  { src: p002, alt: "" },
  { src: p003, alt: "" },
  { src: p004, alt: "" },
  { src: p005, alt: "" },
  { src: p006, alt: "" },
  { src: p007, alt: "" },
  { src: p008, alt: "" },
  { src: p009, alt: "" },
  { src: p010, alt: "" },
  { src: p011, alt: "" },
  { src: p012, alt: "" },
  { src: p013, alt: "" },
  { src: p014, alt: "" },
  { src: p015, alt: "" },
  { src: p016, alt: "" },
  { src: p017, alt: "" },
  { src: p018, alt: "" },
  { src: p019, alt: "" },
  { src: p020, alt: "" },
];
